[phases.setup]
nixPkgs = ["nodejs-22_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "npx tsx scripts/importLUTs.ts luts/",
  "echo 'LUTs imported successfully'"
]

[start]
cmd = "npm start"